### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by gresstant** [eliasdoehne/stellaris-dashboard#19]
```
2019-05-12 23:40:14,792 - flask.app - ERROR - Exception on /timeline/_dash-update-component [POST]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 2292, in wsgi_app
  File "site-packages\flask\app.py", line 1815, in full_dispatch_request
  File "site-packages\flask\app.py", line 1718, in handle_user_exception
  File "site-packages\flask\_compat.py", line 35, in reraise
  File "site-packages\flask\app.py", line 1813, in full_dispatch_request
  File "site-packages\flask\app.py", line 1799, in dispatch_request
  File "site-packages\dash\dash.py", line 1073, in dispatch
  File "site-packages\dash\dash.py", line 969, in add_context
  File "stellarisdashboard\dash_server.py", line 465, in update_content
  File "stellarisdashboard\dash_server.py", line 502, in get_figure_data
  File "stellarisdashboard\dash_server.py", line 519, in get_raw_plot_data_dicts
  File "stellarisdashboard\dash_server.py", line 540, in _get_raw_data_for_line_plot
  File "stellarisdashboard\dash_server.py", line 597, in dict_key_to_legend_label
IndexError: string index out of range
```
This exception only raises when trying to browse information that contains many countries. One country in the game has blank name, and I think this may be related to the problem (not sure).

Non-ASCII characters included in sav file and db file.

[_-795511766.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/3170260/_-795511766.zip)

**Comment by gresstant** [comment]
It seems that this problem can be solved by changing `if words[0][0].islower()` to `if len(words[0]) > 0 and words[0][0].islower():` (stellarisdashboard/dash_server.py, line 597).
