### ISSUE TITLE
Dashboard сan't read saves using cp1252.py

### ISSUE THREAD

**Issue by riddle418** [eliasdoehne/stellaris-dashboard#52]
The error repeats on every save.

> 2021-05-31 21:37:23,670 - stellarisdashboard.parsing.save_parser - INFO - Parsing Save File C:\Users\...\Documents\Paradox Interactive\Stellaris\save games\...\autosave_2202.08.01.sav...
2021-05-31 21:37:24,173 - stellarisdashboard.parsing.save_parser - INFO - Parsed save file C:\Users\...\Documents\Paradox Interactive\Stellaris\save games\...\autosave_2202.08.01.sav in 0.5027387142181396 seconds.
2021-05-31 21:37:24,174 - stellarisdashboard.parsing.save_parser - INFO - Retrieving gamestate for C:\Users\...\Documents\Paradox Interactive\Stellaris\save games\...\autosave_2202.08.01.sav
2021-05-31 21:37:24,175 - stellarisdashboard.parsing.save_parser - ERROR - Error while reading save file C:\Users\...\Documents\Paradox Interactive\Stellaris\save games\...\autosave_2202.08.01.sav:
2021-05-31 21:37:24,176 - stellarisdashboard.parsing.save_parser - ERROR - multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "stellarisdashboard\parsing\save_parser.py", line 269, in parse_save
  File "stellarisdashboard\parsing\save_parser.py", line 387, in parse_save
  File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\encodings\cp1252.py", line 15, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6648: character maps to <undefined>
"""

**Comment by eliasdoehne** [comment]
Hello, thanks for letting me know about this. Could you try with this new release? It should hopefully fix this error.

https://github.com/eliasdoehne/stellaris-dashboard/releases/tag/v2.0.1 

I changed it so it will try with UTF-8 if the 1252 encoding fails. (The 1252 is just a guess based on it being mentioned in the Europa Universalis wiki, unfortunately I could not find any reliable information about the encoding of Stellaris save files...)

**Comment by riddle418** [comment]
Yes, now work. Thank you.

**Comment by eliasdoehne** [comment]
Great, then I will close the issue. Let me know if you find any other problems!
